apiVersion: zinier.tools/v1alpha1
kind: CompositeCloudFront
metadata:
  name: orion-login-app
  namespace: crossplane-system
spec:
  parameters:
    name: orion-login-app
    region: ap-south-1
    domain: login.orion.devzinier.net
    altDomain: "login.orion.devzinier.net"
    zone: orion.devzinier.net
    enabled: true
  compositionUpdatePolicy: Manual