apiVersion: v1
kind: ConfigMap
metadata:
  name:  prod-eu-west-2-k8s-apps-alerts-cm
  namespace: kube-monitoring
data:
  alerts-prod-k8s-apps.rules.yaml: |
    groups:
       - name: "prod-eu-west-2-monitoring-alerts"
         rules:
           - alert: "High Node CPU Usage on euwest2-mon prod-monitoring"
             annotations:
               summary: "k8s Node CPU greater than 80%."
               description: "{{ $labels.tenantname}} In this namespace {{ $labels.kubernetes_io_hostname }} This Node Used more that 80 % of cpu Percentage of CPU."
             expr: |
               (sum(rate(container_cpu_usage_seconds_total{id="/",container!="POD"}[5m])) by (kubernetes_io_hostname) / sum(machine_cpu_cores) by (kubernetes_io_hostname)  * 100) > 80
             for: 2m
             labels:
               prod_mon_euwest2: true
    
           - alert: "High Persistent Volume Usage on euwest2-mon prod-monitoring%"
             annotations:
               summary: "Persistent Volume Usage on euwest2-mon is greater than 90%."
               description: " {{ $labels.namespace}} In this namespace {{ $labels.persistentvolumeclaim }} This persistentvolumeclaim has Used more that 90 Percentage of Volume."
             expr: |
               (sum(kubelet_volume_stats_used_bytes) by (namespace, persistentvolumeclaim) /
               sum(kubelet_volume_stats_capacity_bytes) by (namespace, persistentvolumeclaim)) * 100 > 90
             for: 2m
             labels:
               PVC_alerts: true
    
           - alert: "High Node Disk Usage on euwest2-mon prod-monitoring"
             annotations:
               summary: "Node Disk Usage on euwest2-mon is greater than 85%."
               description: "{{ $labels.tenantname}} in this namespace {{ $labels.kubernetes_io_hostname }} this Node Used more that 85 Percentage of Disk."
             expr: |
               (sum(container_fs_usage_bytes{id="/",container!="POD"}) by (kubernetes_io_hostname) / 
               sum(container_fs_limit_bytes{container!="POD",id="/"}) by (kubernetes_io_hostname)) * 100 > 85
             for: 2m
             labels:
               prod_mon_euwest2: true
    
           - alert: "High Node Memory Usage on euwest2-mon prod-monitoring"
             annotations:
               summary: "Node Memory Usage on euwest2-mon is greater than 80%."
               description: "{{ $labels.tenantname}} in this tenant {{ $labels.kubernetes_io_hostname }} this Node Used more that 80 Percentage of Memory."
             expr: |
               (sum (container_memory_working_set_bytes{id="/",container!="POD"}) by  
               (kubernetes_io_hostname) / sum (machine_memory_bytes{}) by (kubernetes_io_hostname) * 100) > 80
             for: 2m
             labels:
               prod_mon_euwest2: true
    
    
           - alert: "redis pod in uswest1-mon prod-monitoring"
             annotations:
               summary: "redis pods on uswest1-mon is less than 1 "
               description: "{{ $labels.tenantname}} in this tenant {{ $labels.kubernetes_io_hostname }} redis pod in uswest1 is less than 1 ."
             expr: |
               redis_up < 1
             for: 2m
             labels:
               prod_mon_euwest2: true
    
       - name: "prod-eu-west-2-uat-vmtest-apps-alerts"
         rules:
           - alert: "High CPU Usage"
             annotations:
               summary: "{{ $labels.container }} has High CPU usage in {{ $labels.namespace }}"
               description: "{{ $labels.container }} Container is Used more than 80 Percentage of CPU."
             expr: |
               (sum(rate(container_cpu_usage_seconds_total{namespace="uat-vmtest"}[5m])) by (namespace,container,pod)/(sum(kube_pod_container_resource_limits{namespace="uat-vmtest",resource="cpu"}) by (namespace,container,pod)) )*100 > 80
             for: 2m
             labels:
               uat_vmtest: true

           - alert: "High Memory Usage"
             annotations:
               summary: "{{ $labels.container }} has High Memory usage in {{ $labels.namespace }}"
               description: "{{ $labels.container }} Container is Used {{ printf \"%.2f\"   }} % of Memory "
             expr: |
               ((( sum(container_memory_working_set_bytes{namespace="uat-vmtest", container !=""}) by (container,namespace,pod)  /  
               sum(container_spec_memory_limit_bytes{namespace="uat-vmtest",container!=""}) by (namespace,container,pod) ) * 100 ) < +Inf ) > 80
             for: 2m
             labels:
               uat_vmtest: true

           - alert: "Pod Restart"
             annotations:
               summary: "{{ $labels.container }} has Restarted in {{ $labels.namespace }}"
               description: "{{ $labels.container}}  Container has restarted in this pod - {{ $labels.pod }}."
             expr: |
               sum(rate(kube_pod_container_status_restarts_total{namespace="uat-vmtest"}[5m])) by (pod,namespace,container) > 0
             for: 2m
             labels:
               uat_vmtest: true

           - alert: "Number of replicas is 0"
             annotations:
               summary: "{{ $labels.deployment }} has 0 pod in {{ $labels.namespace }}"
               description: "{{ $labels.deployment }} deployment has 0 pods."
             expr: |
               sum(kube_deployment_spec_replicas{namespace="uat-vmtest"} - kube_deployment_status_replicas{namespace="uat-vmtest"}) by (namespace, deployment) > 0
             for: 2m
             labels:
               uat_vmtest: true
    
           - alert: "uptime alerts for uat-vmtest"
             annotations:
               summary: "{{ $labels.service }} is down in {{ $labels.namespace }},{{ $labels.pod }}"
               description: "{{ $labels.service }} service is down."
             expr: |
               sum(up{namespace="uat-vmtest"}) by (service,namespace,pod) < 1
             for: 2m
             labels:
               uat_vmtest: true


       - name: "prod-eu-west-2-prod-cfl-apps-alerts"
         rules:
           - alert: "High CPU Usage"
             annotations:
               summary: "{{ $labels.container }} has High CPU usage in {{ $labels.namespace }}"
               description: "{{ $labels.container }} Container is Used more than 80 Percentage of CPU."
             expr: |
               (sum(rate(container_cpu_usage_seconds_total{namespace="prod-cfl"}[5m])) by (namespace,container,pod)/(sum(kube_pod_container_resource_limits{namespace="prod-cfl",resource="cpu"}) by (namespace,container,pod)) )*100 > 80
             for: 2m
             labels:
               prod_cfl: true

           - alert: "High Memory Usage"
             annotations:
               summary: "{{ $labels.container }} has High Memory usage in {{ $labels.namespace }}"
               description: "{{ $labels.container }} Container Used more than 80 percentage of Memory "
             expr: |
               ((( sum(container_memory_working_set_bytes{namespace="prod-cfl", container !=""}) by (container,namespace,pod)  /  
               sum(container_spec_memory_limit_bytes{namespace="prod-cfl",container!=""}) by (namespace,container,pod) ) * 100 ) < +Inf ) > 80
             for: 2m
             labels:
               prod_cfl: true

           - alert: "Pod Restart"
             annotations:
               summary: "{{ $labels.container }} has Restarted in {{ $labels.namespace }}"
               description: "{{ $labels.container}} Container has restarted in this {{ $labels.pod }}."
             expr: |
               sum(rate(kube_pod_container_status_restarts_total{namespace="prod-cfl"}[5m])) by (pod,namespace,container) > 0
             for: 2m
             labels:
               prod_cfl: true

           - alert: "Number of replicas is 0"
             annotations:
               summary: "{{ $labels.deployment }} has 0 pod in {{ $labels.namespace }}"
               description: "{{ $labels.deployment }} deployment has less than 1 pods."
             expr: |
               sum(kube_deployment_spec_replicas{namespace="prod-cfl"} - kube_deployment_status_replicas{namespace="prod-cfl"}) by (namespace, deployment) > 0
             for: 2m
             labels:
               prod_cfl: true
    
           - alert: "uptime alerts for prod-cfl"
             annotations:
               summary: "{{ $labels.service }} is down in {{ $labels.namespace }},{{ $labels.pod }}"
               description: "{{ $labels.service }} service is down."
             expr: |
               sum(up{namespace="prod-cfl"}) by (service,namespace,pod) < 1
             for: 2m
             labels:
               prod_cfl: true


       - name: "prod-us-west-1-prod-vm-apps-alerts"
         rules:
           - alert: "High CPU Usage"
             annotations:
               summary: "{{ $labels.container }} has High CPU usage in {{ $labels.namespace }}"
               description: "{{ $labels.container }} This Container Used 80 Percentage of CPU."
             expr: |
               (sum(rate(container_cpu_usage_seconds_total{namespace="prod-vm"}[5m])) by (namespace,container,pod)/(sum(kube_pod_container_resource_limits{namespace="prod-vm",resource="cpu"}) by (namespace,container,pod)) )*100 > 80
             for: 2m
             labels:
               prod_vm: true

           - alert: "High Memory Usage"
             annotations:
               summary: "{{ $labels.container }} has High Memory usage in {{ $labels.namespace }}"
               description: "{{ $labels.container }} This Container Used {{ printf \"%.2f\"   }} % of Memory "
             expr: |
               ((( sum(container_memory_working_set_bytes{namespace="prod-vm", container !=""}) by (container,namespace,pod)  /  
               sum(container_spec_memory_limit_bytes{namespace="prod-vm",container!=""}) by (namespace,container,pod) ) * 100 ) < +Inf ) > 80
             for: 2m
             labels:
               prod_vm: true

           - alert: "Pod Restart"
             annotations:
               summary: "{{ $labels.container }} has Restarted in {{ $labels.namespace }}"
               description: "{{ $labels.container}}  This Container has restarted in this {{ $labels.pod }}  More Than 0  Times."
             expr: |
               sum(rate(kube_pod_container_status_restarts_total{namespace="prod-vm"}[5m])) by (pod,namespace,container) > 0
             for: 2m
             labels:
               prod_vm: true

           - alert: "Number of replicas is 0"
             annotations:
               summary: "{{ $labels.deployment }} has 1 pod in {{ $labels.namespace }}"
               description: "{{ $labels.deployment }} This deployment has less than 1 pods."
             expr: |
               sum(kube_deployment_spec_replicas{namespace="prod-vm"} - kube_deployment_status_replicas{namespace="prod-vm"}) by (namespace, deployment) > 0
             for: 2m
             labels:
               prod_vm: true
           
           - alert: "uptime alerts for prod-vm"
             annotations:
               summary: "{{ $labels.service }} is down in {{ $labels.namespace }},{{ $labels.pod }}"
               description: "{{ $labels.service }} service is down."
             expr: |
               sum(up{namespace="prod-vm"}) by (service,namespace,pod) < 1
             for: 2m
             labels:
               prod_vm: true
    
    
    
    
       - name: "prod-us-west-1-kube-logging-alerts"
         rules:
           - alert: "High Memory Usage in namespace kube-logging"
             annotations:
               summary: "Memory Usage in namespace kube-logging greater than 90%."
               description: "{{ $labels.container }} This Container Used {{ printf \"%.2f\"   }} % of Memory "
             expr: |
                ((( sum(container_memory_working_set_bytes{namespace="kube-logging"}) by (namespace,container,pod)  /  
                sum(container_spec_memory_limit_bytes{namespace="kube-logging"}) by (namespace,container,pod) ) * 100 ) < +Inf ) > 90
             for: 2m
             labels:
               prod_monitoring_west: true

           - alert: "Pod Container Restart Rate in namespace kube-logging"
             annotations:
               summary: "Pod Container Restart Rate in namespace kube-logging"
               description: "{{ $labels.container}}  This Container has restarted in this {{ $labels.pod }}  More Than 0  Times."
             expr: |
               sum(rate(kube_pod_container_status_restarts_total{namespace="kube-logging"}[5m])) by (pod,namespace,container) > 0
             for: 2m
             labels:
               prod_monitoring_west: true
    
       - name: "prod-us-west-1-kube-monitoring-alerts"
         rules:
           - alert: "High Memory Usage in namespace kube-monitoring"
             annotations:
               summary: "Memory Usage in namespace kube-monitoring greater than 90%."
               description: "{{ $labels.container }} This Container Used {{ printf \"%.2f\"   }} % of Memory "
             expr: |
                ((( sum(container_memory_working_set_bytes{namespace="kube-monitoring"}) by (namespace,container,pod)  /  
                sum(container_spec_memory_limit_bytes{namespace="kube-monitoring"}) by (namespace,container,pod) ) * 100 ) < +Inf ) > 90
             for: 2m
             labels:
               prod_monitoring_west: true

           - alert: "Pod Container Restart Rate in namespace kube-monitoring"
             annotations:
               summary: "Pod Container Restart Rate in namespace kube-monitoring"
               description: "{{ $labels.container}}  This Container has restarted in this {{ $labels.pod }}  More Than 0  Times."
             expr: |
               sum(rate(kube_pod_container_status_restarts_total{namespace="kube-monitoring"}[5m])) by (pod,namespace,container) > 0
             for: 2m
             labels:
               prod_monitoring_west: true
    
       - name: "prod-us-west-1-kube-system-alerts"
         rules:
           - alert: "High Memory Usage in namespace kube-system"
             annotations:
               summary: "Memory Usage in namespace kube-system greater than 90%."
               description: "{{ $labels.container }} This Container Used {{ printf \"%.2f\"   }} % of Memory "
             expr: |
                ((( sum(container_memory_working_set_bytes{namespace="kube-system"}) by (namespace,container,pod)  /  
                sum(container_spec_memory_limit_bytes{namespace="kube-system"}) by (namespace,container,pod) ) * 100 ) < +Inf ) > 90
             for: 2m
             labels:
               prod_monitoring_west: true

           - alert: "Pod Container Restart Rate in namespace kube-system"
             annotations:
               summary: "Pod Container Restart Rate in namespace kube-system"
               description: "{{ $labels.container}}  This Container has restarted in this {{ $labels.pod }}  More Than 0  Times."
             expr: |
               sum(rate(kube_pod_container_status_restarts_total{namespace="kube-system"}[5m])) by (pod,namespace,container) > 0
             for: 2m
             labels:
               prod_monitoring_west: true
    
       - name: "prod-us-west-1-kube-tracing-alerts"
         rules:
           - alert: "High Memory Usage in namespace kube-tracing"
             annotations:
               summary: "Memory Usage in namespace kube-tracing greater than 90%."
               description: "{{ $labels.container }} This Container Used {{ printf \"%.2f\"   }} % of Memory "
             expr: |
                ((( sum(container_memory_working_set_bytes{namespace="kube-tracing"}) by (namespace,container,pod)  /  
                sum(container_spec_memory_limit_bytes{namespace="kube-tracing"}) by (namespace,container,pod) ) * 100 ) < +Inf ) > 90
             for: 2m
             labels:
               prod_monitoring_west: true

           - alert: "Pod Container Restart Rate in namespace kube-tracing"
             annotations:
               summary: "Pod Container Restart Rate in namespace kube-tracing"
               description: "{{ $labels.container}}  This Container has restarted in this {{ $labels.pod }}  More Than 0  Times."
             expr: |
               sum(rate(kube_pod_container_status_restarts_total{namespace="kube-tracing"}[5m])) by (pod,namespace,container) > 0
             for: 2m
             labels:
               prod_monitoring_west: true