apiVersion: v1
kind: ConfigMap
metadata:
  name:  hope-cluster-dev-k8s-apps-alerts-cm
  namespace: monitoring        # need to replace
data:
  alert-prod-k8s-apps.rules.yaml: |
   groups:
     - name: "prod-dev-karpenter-alerts"
       rules:
         - alert: "High Memory Usage in namespace karpenter"
           annotations:
             summary: "Memory Usage in namespace karpenter greater than 90%."
             description: "{{ $labels.container }} This Container Used {{ printf \"%.2f\"   }} % of Memory "
           expr: |
              ((( sum(container_memory_working_set_bytes{namespace="karpenter"}) by (namespace,container,pod)  /  
              sum(container_spec_memory_limit_bytes{namespace="karpenter"}) by (namespace,container,pod) ) * 100 ) < +Inf ) > 90
           for: 1m
           labels:
             prod_monitoring_dev: true

         - alert: "Pod Container Restart Rate in namespace karpenter"
           annotations:
             summary: "Pod Container Restart Rate in namespace karpenter"
             description: "{{ $labels.container}}  This Container has restarted in this {{ $labels.pod }}  More Than 0  Times."
           expr: |
             sum(rate(kube_pod_container_status_restarts_total{namespace="karpenter"}[5m])) by (pod,namespace,container) > 0
           for: 1m
           labels:
             prod_monitoring_dev: true
 
     - name: "prod-dev-monitoring-alerts"
       rules:
         - alert: "High Memory Usage in namespace monitoring"
           annotations:
             summary: "Memory Usage in namespace monitoring greater than 90%."
             description: "{{ $labels.container }} This Container Used {{ printf \"%.2f\"   }} % of Memory "
           expr: |
              ((( sum(container_memory_working_set_bytes{namespace="monitoring"}) by (namespace,container,pod)  /  
              sum(container_spec_memory_limit_bytes{namespace="monitoring"}) by (namespace,container,pod) ) * 100 ) < +Inf ) > 90
           for: 1m
           labels:
             prod_monitoring_dev: true

         - alert: "Pod Container Restart Rate in namespace monitoring"
           annotations:
             summary: "Pod Container Restart Rate in namespace monitoring"
             description: "{{ $labels.container}}  This Container has restarted in this {{ $labels.pod }}  More Than 0  Times."
           expr: |
             sum(rate(kube_pod_container_status_restarts_total{namespace="monitoring"}[5m])) by (pod,namespace,container) > 0
           for: 1m
           labels:
             prod_monitoring_dev: true
 
     - name: "prod-dev-kube-system-alerts"
       rules:
         - alert: "High Memory Usage in namespace kube-system"
           annotations:
             summary: "Memory Usage in namespace kube-system greater than 90%."
             description: "{{ $labels.container }} This Container Used {{ printf \"%.2f\"   }} % of Memory "
           expr: |
              ((( sum(container_memory_working_set_bytes{namespace="kube-system"}) by (namespace,container,pod)  /  
              sum(container_spec_memory_limit_bytes{namespace="kube-system"}) by (namespace,container,pod) ) * 100 ) < +Inf ) > 90
           for: 1m
           labels:
             prod_monitoring_dev: true

         - alert: "Pod Container Restart Rate in namespace kube-system"
           annotations:
             summary: "Pod Container Restart Rate in namespace kube-system"
             description: "{{ $labels.container}}  This Container has restarted in this {{ $labels.pod }}  More Than 0  Times."
           expr: |
             sum(rate(kube_pod_container_status_restarts_total{namespace="kube-system"}[5m])) by (pod,namespace,container) > 0
           for: 1m
           labels:
             prod_monitoring_dev: true
 
     - name: "prod-dev-kube-tracing-alerts"
       rules:
         - alert: "High Memory Usage in namespace kube-tracing"
           annotations:
             summary: "Memory Usage in namespace kube-tracing greater than 90%."
             description: "{{ $labels.container }} This Container Used {{ printf \"%.2f\"   }} % of Memory "
           expr: |
              ((( sum(container_memory_working_set_bytes{namespace="kube-tracing"}) by (namespace,container,pod)  /  
              sum(container_spec_memory_limit_bytes{namespace="kube-tracing"}) by (namespace,container,pod) ) * 100 ) < +Inf ) > 90
           for: 1m
           labels:
             prod_monitoring_dev: true

         - alert: "Pod Container Restart Rate in namespace kube-tracing"
           annotations:
             summary: "Pod Container Restart Rate in namespace kube-tracing"
             description: "{{ $labels.container}}  This Container has restarted in this {{ $labels.pod }}  More Than 0  Times."
           expr: |
             sum(rate(kube_pod_container_status_restarts_total{namespace="kube-tracing"}[5m])) by (pod,namespace,container) > 0
           for: 1m
           labels:
             prod_monitoring_dev: true
   
     - name: "prod-dev-keycloak-alerts"
       rules:
         - alert: "High Memory Usage in namespace keycloak"
           annotations:
             summary: "Memory Usage in namespace keycloak greater than 90%."
             description: "{{ $labels.container }} This Container Used {{ printf \"%.2f\"   }} % of Memory "
           expr: |
              ((( sum(container_memory_working_set_bytes{namespace="keycloak"}) by (namespace,container,pod)  /  
              sum(container_spec_memory_limit_bytes{namespace="keycloak"}) by (namespace,container,pod) ) * 100 ) < +Inf ) > 90
           for: 1m
           labels:
             prod_monitoring_dev: true

         - alert: "Pod Container Restart Rate in namespace keycloak"
           annotations:
             summary: "Pod Container Restart Rate in namespace keycloak"
             description: "{{ $labels.container}}  This Container has restarted in this {{ $labels.pod }}  More Than 0  Times."
           expr: |
             sum(rate(kube_pod_container_status_restarts_total{namespace="keycloak"}[5m])) by (pod,namespace,container) > 0
           for: 1m
           labels:
             prod_monitoring_dev: true
   
     - name: "prod-dev-lss-poc-alerts"
       rules:
         - alert: "High Memory Usage in namespace lss-poc"
           annotations:
             summary: "Memory Usage in namespace lss-poc greater than 90%."
             description: "{{ $labels.container }} This Container Used {{ printf \"%.2f\"   }} % of Memory "
           expr: |
              ((( sum(container_memory_working_set_bytes{namespace="lss-poc"}) by (namespace,container,pod)  /  
              sum(container_spec_memory_limit_bytes{namespace="lss-poc"}) by (namespace,container,pod) ) * 100 ) < +Inf ) > 90
           for: 1m
           labels:
             prod_monitoring_dev: true

         - alert: "Pod Container Restart Rate in namespace lss-poc"
           annotations:
             summary: "Pod Container Restart Rate in namespace lss-poc"
             description: "{{ $labels.container}}  This Container has restarted in this {{ $labels.pod }}  More Than 0  Times."
           expr: |
             sum(rate(kube_pod_container_status_restarts_total{namespace="lss-poc"}[5m])) by (pod,namespace,container) > 0
           for: 1m
           labels:
             prod_monitoring_dev: true
   
     - name: "prod-dev-openfaas-alerts"
       rules:
         - alert: "High Memory Usage in namespace openfaas"
           annotations:
             summary: "Memory Usage in namespace openfaas greater than 90%."
             description: "{{ $labels.container }} This Container Used {{ printf \"%.2f\"   }} % of Memory "
           expr: |
              ((( sum(container_memory_working_set_bytes{namespace="openfaas"}) by (namespace,container,pod)  /  
              sum(container_spec_memory_limit_bytes{namespace="openfaas"}) by (namespace,container,pod) ) * 100 ) < +Inf ) > 90
           for: 1m
           labels:
             prod_monitoring_dev: true

         - alert: "Pod Container Restart Rate in namespace openfaas"
           annotations:
             summary: "Pod Container Restart Rate in namespace openfaas"
             description: "{{ $labels.container}}  This Container has restarted in this {{ $labels.pod }}  More Than 0  Times."
           expr: |
             sum(rate(kube_pod_container_status_restarts_total{namespace="openfaas"}[5m])) by (pod,namespace,container) > 0
           for: 1m
           labels:
             prod_monitoring_dev: true
   
     - name: "prod-dev-postgres-alerts"
       rules:
         - alert: "High Memory Usage in namespace postgres"
           annotations:
             summary: "Memory Usage in namespace postgres greater than 90%."
             description: "{{ $labels.container }} This Container Used {{ printf \"%.2f\"   }} % of Memory "
           expr: |
              ((( sum(container_memory_working_set_bytes{namespace="postgres"}) by (namespace,container,pod)  /  
              sum(container_spec_memory_limit_bytes{namespace="postgres"}) by (namespace,container,pod) ) * 100 ) < +Inf ) > 90
           for: 1m
           labels:
             prod_monitoring_dev: true

         - alert: "Pod Container Restart Rate in namespace postgres"
           annotations:
             summary: "Pod Container Restart Rate in namespace postgres"
             description: "{{ $labels.container}}  This Container has restarted in this {{ $labels.pod }}  More Than 0  Times."
           expr: |
             sum(rate(kube_pod_container_status_restarts_total{namespace="postgres"}[5m])) by (pod,namespace,container) > 0
           for: 1m
           labels:
             prod_monitoring_dev: true
   
     - name: "prod-dev-shared-services-alerts"
       rules:
         - alert: "High Memory Usage in namespace shared-services"
           annotations:
             summary: "Memory Usage in namespace shared-services greater than 90%."
             description: "{{ $labels.container }} This Container Used {{ printf \"%.2f\"   }} % of Memory "
           expr: |
              ((( sum(container_memory_working_set_bytes{namespace="shared-services"}) by (namespace,container,pod)  /  
              sum(container_spec_memory_limit_bytes{namespace="shared-services"}) by (namespace,container,pod) ) * 100 ) < +Inf ) > 90
           for: 1m
           labels:
             prod_monitoring_dev: true

         - alert: "Pod Container Restart Rate in namespace shared-services"
           annotations:
             summary: "Pod Container Restart Rate in namespace shared-services"
             description: "{{ $labels.container}}  This Container has restarted in this {{ $labels.pod }}  More Than 0  Times."
           expr: |
             sum(rate(kube_pod_container_status_restarts_total{namespace="shared-services"}[5m])) by (pod,namespace,container) > 0
           for: 1m
           labels:
             prod_monitoring_dev: true
   
     - name: "prod-dev-z-sidekick-alerts"
       rules:
         - alert: "High Memory Usage in namespace z-sidekick"
           annotations:
             summary: "Memory Usage in namespace z-sidekick greater than 90%."
             description: "{{ $labels.container }} This Container Used {{ printf \"%.2f\"   }} % of Memory "
           expr: |
              ((( sum(container_memory_working_set_bytes{namespace="z-sidekick"}) by (namespace,container,pod)  /  
              sum(container_spec_memory_limit_bytes{namespace="z-sidekick"}) by (namespace,container,pod) ) * 100 ) < +Inf ) > 90
           for: 1m
           labels:
             prod_monitoring_dev: true

         - alert: "Pod Container Restart Rate in namespace z-sidekick"
           annotations:
             summary: "Pod Container Restart Rate in namespace z-sidekick"
             description: "{{ $labels.container}}  This Container has restarted in this {{ $labels.pod }}  More Than 0  Times."
           expr: |
             sum(rate(kube_pod_container_status_restarts_total{namespace="z-sidekick"}[5m])) by (pod,namespace,container) > 0
           for: 1m
           labels:
             prod_monitoring_dev: true