apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    application: gdz
    http_target: process-event
    pyrra.dev/app: prod-vm
  name: prodvm-availability
  namespace: kube-monitoring
spec:
  alerting: {}
  description:  availability of gdz-prod-vm (4xx,5xx errors)
  indicator:
    ratio:
      errors:
        metric:  calls_total{service_name="gdz-prod-vm", http_status_code!~"2..", http_target=~"/event/start|/process/start"}
      total:
        metric:  calls_total{service_name="gdz-prod-vm", http_target=~"/event/start|/process/start"}
  target: "95.5"
  window: 1w

---

apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    application: gdz
    pyrra.dev/app: prod-vm
    role: alert-rules
  name: prodvm-loglevel
  namespace: kube-monitoring
spec:
  alerting: {}
  description: error logs in prod-vm gdz
  indicator:
    ratio:
      errors:
        metric: logback_events_total{application="gdz", namespace="prod-vm",level="error"}
      total:
        metric: logback_events_total{application="gdz", namespace="prod-vm"}
  target: "95.5"
  window: 1w

---

apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    application: gdz
    pyrra.dev/app: prod-vm
    role: alert-rules
  name: prodvm-targetwiseavailability
  namespace: kube-monitoring
spec:
  alerting: {}
  description:  uri wise http requests errors
  indicator:
    ratio:
      errors:
        metric:  calls_total{service_name="gdz-prod-vm", http_status_code!~"2..", http_target=~"/.*"}
      grouping:
        - http_target
      total:
        metric:  calls_total{service_name="gdz-prod-vm", http_target=~"/.*"}
  target: "95.5"
  window: 1w

---

apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    application: gdz
    pyrra.dev/app: prod-vm
    role: alert-rules
  name: prodvm-latency
  namespace: kube-monitoring
spec:
  alerting: {}
  description: GDZ latency duration.
  indicator:
    latency:
      success:
        metric: http_server_requests_seconds_bucket{application="gdz", namespace="prod-vm", uri=~"/process/start|/process/bufferedSync|/event/start|/query/read|/process/resume|/session/login", le="1.073741824"}
      total:
        metric: http_server_requests_seconds_count{application="gdz", namespace="prod-vm", uri=~"/process/start|/process/bufferedSync|/event/start|/query/read|/process/resume|/session/login"}
  target: "95.5"
  window: 2w

