apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    application: gdz
    http_target: process-start
    pyrra.dev/app: uat-vm
  name: uat-vm-availability
  namespace: kube-monitoring
spec:
  alerting: {}
  description:  availability of gdz-uat-vmtest (4xx,5xx errors)
  indicator:
    ratio:
      errors:
        metric:  calls_total{service_name="gdz-uat-vmtest", http_status_code!~"2..", http_target="/process/start"}
      total:
        metric:  calls_total{service_name="gdz-uat-vmtest",http_target="/process/start"}
  target: "95.5"
  window: 1w

---

apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    application: gdz
    pyrra.dev/app: uat-vm
    role: alert-rules
  name: uat-vm-loglevel
  namespace: kube-monitoring
spec:
  alerting: {}
  description: error logs in uat-vmtest gdz
  indicator:
    ratio:
      errors:
        metric: logback_events_total{application="gdz", namespace="uat-vmtest",level="error"}
      total:
        metric: logback_events_total{application="gdz", namespace="uat-vmtest"}
  target: "95.5"
  window: 1w

---

apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    application: gdz
    pyrra.dev/app: uat-vm
    role: alert-rules
  name: uat-vm-latency
  namespace: kube-monitoring
spec:
  alerting: {}
  description: GDZ latency duration.
  indicator:
    latency:
      success:
        metric: http_server_requests_seconds_bucket{application="gdz", namespace="uat-vmtest", uri="/process/start", le="5.726623061"}
      total:
        metric: http_server_requests_seconds_count{application="gdz", namespace="uat-vmtest", uri="/process/start"}
  target: "95.0"
  window: 1w