apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    application: gdz
    http_target: process-start
    pyrra.dev/app: prod-vm
  name: prod-vm-availability
  namespace: kube-monitoring
spec:
  alerting: {}
  description:  availability of gdz-prod-vm (4xx,5xx errors)
  indicator:
    ratio:
      errors:
        metric:  calls_total{service_name="gdz-prod-vm", http_status_code!~"2..", http_target="/process/start"}
      total:
        metric:  calls_total{service_name="gdz-prod-vm",http_target="/process/start"}
  target: "95.5"
  window: 1w

---

apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    application: gdz
    pyrra.dev/app: prod-vm
    role: alert-rules
  name: prod-vm-loglevel
  namespace: kube-monitoring
spec:
  alerting: {}
  description: error logs in prod-vm gdz
  indicator:
    ratio:
      errors:
        metric: logback_events_total{application="gdz", namespace="prod-vm",level="error"}
      total:
        metric: logback_events_total{application="gdz", namespace="prod-vm"}
  target: "95.5"
  window: 1w

---

apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    application: gdz
    pyrra.dev/app: prod-vm
    role: alert-rules
  name: prod-vm-latency
  namespace: kube-monitoring
spec:
  alerting: {}
  description: GDZ latency duration.
  indicator:
    latency:
      success:
        metric: http_server_requests_seconds_bucket{application="gdz", namespace="prod-vm", uri="/process/start", le="7.158278826"}
      total:
        metric: http_server_requests_seconds_count{application="gdz", namespace="prod-vm", uri="/process/start"}
  target: "95.0"
  window: 1w