apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    application: gdz
    http_target: process-start
    pyrra.dev/app: prod-cfl
  name: prod-cfl-availability
  namespace: kube-monitoring
spec:
  alerting: {}
  description:  availability of gdz-prod-cfl (4xx,5xx errors)
  indicator:
    ratio:
      errors:
        metric:  calls_total{service_name="gdz-prod-cfl", http_status_code!~"2..", http_target="/process/start"}
      total:
        metric:  calls_total{service_name="gdz-prod-cfl",http_target="/process/start"}
  target: "95.5"
  window: 1w

---

apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    application: gdz
    pyrra.dev/app: prod-cfl
    role: alert-rules
  name: prod-cfl-loglevel
  namespace: kube-monitoring
spec:
  alerting: {}
  description: error logs in prod-cfl gdz
  indicator:
    ratio:
      errors:
        metric: logback_events_total{application="gdz", namespace="prod-cfl",level="error"}
      total:
        metric: logback_events_total{application="gdz", namespace="prod-cfl"}
  target: "95.5"
  window: 1w
---

apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    application: gdz
    pyrra.dev/app: prod-cfl
    role: alert-rules
  name: prod-cfl-latency
  namespace: kube-monitoring
spec:
  alerting: {}
  description: GDZ latency duration.
  indicator:
    latency:
      success:
        metric: http_server_requests_seconds_bucket{application="gdz", namespace="prod-cfl", uri="/process/start", le="4.294967296"}
      total:
        metric: http_server_requests_seconds_count{application="gdz", namespace="prod-cfl", uri="/process/start"}
  target: "95.0"
  window: 1w